### PR TITLE
Add a couple of precompiles

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by yurivish** [comment]
Hi Tim! I'm wondering – what does executing these precompile statements get you beyond the result of calling the functions for the first time, which would compile them at the point of first use?

**Comment by timholy** [comment]
Lower latency on first use. I didn't measure here, but for reference: https://github.com/JuliaImages/ImageFiltering.jl/pull/201.

I'm not sure the ones here "work," though; there are a few cases that don't, for reasons the community has yet to fully understand. (E.g., https://github.com/JuliaLang/julia/issues/38983.) But eventually they will start working, so it's probably not bad to have them.

**Comment by yurivish** [comment]
Thanks for the links! Just to make sure I understand, the tradeoff here is to incur the latency cost every time the package is loaded, regardless of whether any of these functions is used during the session, rather than incurring it at the first point of use? I haven’t been following the recent compiler improvements but I know there are varying levels of precompilation.

I can see why this might be preferable since one can go and make coffee or someone while the “using” statement is being executed...

**Comment by timholy** [comment]
> the tradeoff here is to incur the latency cost every time the package is loaded,

No, the cost of `precompile` is paid just when it's precompiled. I.e., when the package is being built. (`Precompiling SignedDistanceFields...`) There's a *small* extra penalty to load the type-inferred MethodInstances but that's much smaller than needing to run inference every time you use the methods.

**Comment by yurivish** [comment]
Ah, got it. Thanks!

**Comment by timholy** [comment]
Your question was a good one, though; I remember thinking the same thing. It was also timely, as it prompted me to explain this specific point in https://github.com/JuliaLang/www.julialang.org/pull/1111. (In the preview, scroll down to "It might be natural to wonder...")

**Pull request merged**
